services:
  - type: redis
    name: axionix-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: anywhere
    plan: free

  - type: web
    name: axionix-worker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: axionix-redis
          property: connectionString
      - key: DATABASE_URL
        sync: false
